platform :ios, '9.0'

target 'RouteExample' do
  use_frameworks!

  pod 'Route', :path => '../'
  pod 'TableAdapter', '~>1.1.0'
  
end

target 'RouteExampleUITests' do
  use_frameworks!

  pod 'Route', :path => '../'
  
end
